docker rm api -f
docker rm customer-profile-service-api-migration-1 -f
docker rm cache -f
docker rm db -f
docker rm customer-profile-service-api-prometheus-1 -f
docker image rm api
docker image rm flyway/flyway
docker image rm customer-profile-service-api
docker image rm postgres
docker image rm redis
docker image rm prom/prometheus